# Generated by Django 5.2.4 on 2025-07-23 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0003_comment_follow_reaction"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reaction",
            old_name="like_id",
            new_name="reaction_id",
        ),
    ]
