# Generated by Django 5.2.4 on 2025-07-25 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0004_rename_like_id_reaction_reaction_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="age",
        ),
    ]
