# Generated by Django 5.2.4 on 2025-07-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0005_remove_user_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="DOB",
            field=models.DateField(null=True),
        ),
    ]
