# Generated by Django 5.2.6 on 2025-11-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_postinteraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='attachment',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='attachment',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
